'use strict'

module.exports = (grunt) ->
  fs = undefined
  isModified = undefined
  fs = require('fs')

  isModified = (filepath) ->
    modified = undefined
    now = undefined
    now = new Date
    modified = fs.statSync(filepath).mtime
    now - modified < 10000

  grunt.loadNpmTasks 'grunt-browserify'
  grunt.loadNpmTasks 'grunt-contrib-clean'
  grunt.loadNpmTasks 'grunt-bearcat-browser'
  grunt.loadNpmTasks 'grunt-coffeelint'
  grunt.loadNpmTasks 'grunt-contrib-coffee'
  grunt.loadNpmTasks 'grunt-contrib-watch'
  grunt.loadNpmTasks 'grunt-contrib-uglify'

  src = []
  # Project configuration.
  grunt.initConfig
    pkg: grunt.file.readJSON('package.json')

    uglify:
      options:
        beautify: true
        compress: true
        wrap: true
#        sourceMap: true
#        sourceMapName: 'static/script/release/bundle.js.map'
      files:
        src: [
#          'static/script/**/*.js'
#          '!static/script/release/**/*.js'
#          '!static/script/commons/Constants.js'
#          '!static/script/commons/LocalizeContext.js'
#          '!static/script/net/GameProtocol.js'
#          '!static/script/util/UILoader.js'
        ]
        dest: 'static/script/release/bundle.js'

    bearcat_browser:
      default:
        dest: 'bearcat-bootstrap.js'
        context: 'context.json'

    browserify:
      standalone:
        src: ['client.js']
        dest: 'static/main.js'
        options: {}

    coffee:
      options:
        sourceMap: true
        bare: true
        force: true
      all:
        expand: true
        cwd: 'static/coffee/'
        src: '**/*.coffee'
        dest: 'static/script'
        ext: '.js'
      modified:
        expand: true
        cwd: 'static/coffee/'
        src: '**/*.coffee'
        dest: 'static/script'
        ext: '.js'
        filter: isModified

    coffeelint:
      options:
        force: true
        max_line_length:
          "level": "ignore"
      all:
        expand: true
        cwd: 'static/coffee/'
        src: '**/*.coffee'
      modified:
        expand: true
        cwd: '../script/'
        src: '**/*.coffee'
        filter: isModified

    watch:
      coffeescript:
        files: ['static/coffee//**/*.coffee']
        tasks: [
#          'coffeelint:modified'
          'coffee:modified'
        ]
  # Default task.
  grunt.registerTask 'default', [
    'uglify'
    'bearcat_browser'
    'browserify'
  ]
  grunt.registerTask 'script', [
    'coffee:all'
    'watch'
  ]
  grunt.registerTask 'scriptNoWatch', [
    'coffee:all'
  ]

# ---
# generated by js2coffee 2.1.0