// Generated by CoffeeScript 1.12.7

/**
  Scene Base Object
  场景基类
  create by byron.song on 2015.10.16
 */
var BaseScene;

BaseScene = function() {
  this.$id = 'baseScene';
  this.$init = 'init';
  this.ctor = null;
  this.$logger = null;
  this.$ez = null;
  this.$resourceUtil = null;
  this.$logger = null;
  this.$ccbLoader = null;
  this.$socketClient = null;
  this.$display = null;
  this.$userData = null;
  this.$gTblContainer = null;
};

BaseScene.prototype.init = function() {
  var self;
  self = this;
  this.ctor = cc.Scene.extend({
    ctor: function() {
      this._super();
      this.ez = self.$ez;
      this.display = self.$display;
      this.userData = self.$userData;
      this.gTblContainer = self.$gTblContainer;
      this.ccbLoader = self.$ccbLoader;
    },
    onEnter: function() {
      return this._super();
    },
    onExit: function() {
      return this._super();
    },

    /**
      * 发送Socket请求
      *
     */
    send: function(req, control, isSyncMessage) {}
  });
};
